### PR TITLE
change all "error:" to "(?:warning|error):"

### PR DESCRIPTION
**Pull request by brianyu28**
Addressing #36

### CODE REVIEW

**Comment by dmalan** [comment]
Can all of these definitely be either warnings or errors? Or are some only errors, irrespective of `-Werror`?

**Comment by brianyu28** [comment]
The ones that can be warnings or errors should already be marked as `(?:warning|error):`, even prior to this PR. I'm fairly certain that all of these changes included here are ones that are only `error`.

When you posted the issue, I thought you meant that for consistency, we should turn everything into `(?:warning|error):` so we wouldn't have to worry now or in the future about checking to see whether a given message could be either one. If I misunderstood, then we can probably just close this and continue with the existing workflow.

**Comment by dmalan** [comment]
Oh I just meant we should handle both _if_ we might see the message as either a warning or an error, depending on flags. Feels bad to add "warning|" to the regexes if we'll never encounter them as warnings.

**Comment by brianyu28** [comment]
Makes sense, I agree. Yeah, the ones that can be warnings are already marked as `(?:warning|error):`. Sorry for the misinterpretation, closing this now.

**Pull request closed without merging**
