### PR TITLE
removed pexpect, fixed windows

### PR DESCRIPTION
**Pull request by kzidane**

### CODE REVIEW

**Comment by kzidane** [comment]
Looks like it's different as you guessed.

**Comment by crossroads1112** [comment]
@kzidane, I thought this was a pull request into develop. Why did you merge directly into master instead of going through develop? Now develop is in an inconsistent state.

**Comment by kzidane** [comment]
My bad. I thought develop had unfinished work at the time. Are we all set?

**Comment by crossroads1112** [comment]
Nbd, yeah I think we should be.

**Pull request merged**
